name: CI
on: [pull_request, push]
jobs:
  mix_test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.10.4"
              otp: "23"
          - pair:
              elixir: "1.12.3"
              otp: "24"
            lint: lint

    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3.2.1
        with:
          path: deps
          key: deps-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-
      - uses: actions/cache@v3.2.1
        with:
          path: _build
          key: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: mix deps.get
      - run: mix format --check-formatted
        if: ${{ matrix.lint }}
      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}
      - run: mix test
